Trekster_web/Trekster_web/Controllers/AccountsController.cs
using System.Security.Claims;
using AutoMapper;
using BusinessLogic.Models;
using BusinessLogic.Services.ServiceInterfaces;
using Infrastructure.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Trekster_web.ControllerServices.Interfaces;
using Trekster_web.Filters;
using Trekster_web.Models;

namespace Trekster_web.Controllers
{
    [AuthorizeFilter]
    public class AccountsController : Controller
    {
        private readonly ICurrencyService _currencies;
        private readonly IAccountControllerService _account;

        public AccountsController(ICurrencyService currencies,
                                  IAccountControllerService account)
        {
            _currencies = currencies;
            _account = account;
        }

        public async Task<IActionResult> Index()
        {
            var accountsVM = new AccountsVM();
            accountsVM.AccountsSummary = _account.GetAccountsInfo();

            return View(accountsVM);
        }

        public IActionResult Create()
        {
            var accountsVM = new AccountsVM();

            accountsVM.StartBalances = new Dictionary<string, float>();

            foreach (var tmp in _currencies.GetAll())
            {
                accountsVM.StartBalances.Add(tmp.Name, 0);
            }

            return View(accountsVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AccountsVM accountsVM)
        {
            if (ModelState.IsValid && _account.StartBalancesNotEmpty(accountsVM))
            {
                _account.SaveAccount(accountsVM);

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(accountsVM);
            }
        }
    }
}

Trekster_web/Trekster_web/Controllers/ExpensesController.cs
using BusinessLogic.Services.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using Trekster_web.ControllerServices.Interfaces;
using Trekster_web.Filters;
using Trekster_web.Models;

namespace Trekster_web.Controllers
{
    [AuthorizeFilter]
    public class ExpensesController : Controller
    {
        private readonly IExpensesControllerService _expenses;

        public ExpensesController(IExpensesControllerService expenses)
        {
            _expenses = expenses;
        }

        public IActionResult Index()
        {
            var expencesVM = new ExpencesVM();
            expencesVM.Summary = _expenses.GetSummary();
            expencesVM.ExpencesByCategory = _expenses.GetExpencesByCategory();
            return View(expencesVM);
        }
    }
}

Trekster_web/Trekster_web/Controllers/HistoryController.cs
using AutoMapper;
using BusinessLogic.Models;
using BusinessLogic.Services.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using Trekster_web.ControllerServices.Interfaces;
using Trekster_web.Filters;
using Trekster_web.Models;

namespace Trekster_web.Controllers
{
    [AuthorizeFilter]
    public class HistoryController : Controller
    {
        private readonly ITransactionService _transaction;
        private readonly IAccountService _account;
        private readonly ICategoryService _category;
        private readonly ICurrencyService _currency;
        private readonly IStartBalanceService _startBalance;
        private readonly IMapper _mapper;
        private readonly IHistoryControllerService _history;

        public HistoryController(ITransactionService transaction,
                                 IAccountService account,
                                 ICategoryService category,
                                 ICurrencyService currency,
                                 IStartBalanceService startBalance,
                                 IMapper mapper,
                                 IHistoryControllerService history)
        {
            _transaction = transaction;
            _account = account;
            _category = category;
            _currency = currency;
            _mapper = mapper;
            _startBalance = startBalance;
            _history = history;
        }

        public IActionResult Index()
        {
            var historyVM = new HistoryVM();
            historyVM.Transactions = _transaction.GetAllForUser();
            historyVM.TransactionInfo = _history.GetTransactionInfo();
            return View(historyVM);
        }

        public async Task<IActionResult> EditTransaction(int id)
        {
            ViewData["AccountsAndCurency"] = _history.GetListOfAccounts();
            ViewData["Categories"] = new SelectList(_category.GetAll(), "Id", "Name");

            var transactionVM = _mapper.Map<TransactionVM>(_transaction.GetById(id));
            return View(transactionVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditTransaction(int id, TransactionVM transactionVM)
        {
            if (ModelState.IsValid)
            {
                _history.SaveTransaction(transactionVM);
                return RedirectToAction(nameof(Index));
            }

            return View(transactionVM);
        }

        public async Task<IActionResult> DeleteTransaction(int id)
        {
            return View(_mapper.Map<TransactionVM>(_transaction.GetById(id)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTransaction(int id, TransactionVM transactionVM)
        {
            if (ModelState.IsValid)
            {
                _transaction.Delete(id);
                return RedirectToAction(nameof(Index));
            }

            return View(transactionVM);
        }
    }
}

Trekster_web/Trekster_web/Controllers/ProfitsController.cs
using Microsoft.AspNetCore.Mvc;
using Trekster_web.ControllerServices.Interfaces;
using Trekster_web.Filters;
using Trekster_web.Models;

namespace Trekster_web.Controllers
{
    [AuthorizeFilter]
    public class ProfitsController : Controller
    {
        private readonly IProfitsControllerService _profits;

        public ProfitsController(IProfitsControllerService profits)
        {
            _profits = profits;
        }

        public IActionResult Index()
        {
            var profitVM = new ProfitsVM();
            profitVM.Summary = _profits.GetSummary();
            profitVM.ProfitsByCategory = _profits.GetProfitsByCategory();
            return View(profitVM);
        }
    }
}

Trekster_web/Trekster_web/Views/Shared/_Layout.cshtml
@using Infrastructure.Entities;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Trekster_web.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trekster</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-xs-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Accounts" asp-action="Index">Рахунки</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="History" asp-action="Index">Історія</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Profits" asp-action="Index">Доходи</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Expenses" asp-action="Index">Витрати</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Settings" asp-action="Index">Налаштування</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Trekster - Privacy
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>